function testSRRCdesigner_generatehdl(filtobj)
%  TESTSRRCDESIGNER_GENERATEHDL   Function to generate HDL for filter object.
%  Generated by MATLAB(R) 9.4 and Filter Design HDL Coder 3.1.3.
%  Generated on: 2022-03-03 12:46:53
%  -------------------------------------------------------------
%  HDL Code Generation Options:
%  InputType: signed/unsigned
%  ResetType: Synchronous
%  FIRAdderStyle: tree
%  MultiplierInputPipeline: 1
%  MultiplierOutputPipeline: 1
%  OptimizeForHDL: on
%  HDLSimCmd: vsim %%s.%%s\n
%  TargetDirectory: A:\School\EE465\EE465\examples\matlab
%  AddPipelineRegisters: on
%  Name: testSRRCdesigner
%  TargetLanguage: Verilog
%  MultifileTestBench: on
%  TestBenchStimulus: impulse step ramp chirp noise 
%  InitializeTestBenchInputs: on
%  GenerateCoSimBlock: on
%  GenerateHDLTestbench: on
% 
%  Filter Settings:
%  Discrete-Time FIR Filter (real)
%  -------------------------------
%  Filter Structure  : Direct-Form FIR
%  Filter Length     : 101
%  Stable            : Yes
%  Linear Phase      : Yes (Type 1)

%  -------------------------------------------------------------

% Generating HDL code
generatehdl(filtobj, 'InputType', 'signed/unsigned',... 
               'ResetType', 'Synchronous',... 
               'FIRAdderStyle', 'tree',... 
               'MultiplierInputPipeline', 1,... 
               'MultiplierOutputPipeline', 1,... 
               'OptimizeForHDL', 'on',... 
               'HDLSimCmd', 'vsim %s.%s\n',... 
               'TargetDirectory', 'A:\School\EE465\EE465\examples\matlab',... 
               'AddPipelineRegisters', 'on',... 
               'Name', 'testSRRCdesigner',... 
               'TargetLanguage', 'Verilog',... 
               'MultifileTestBench', 'on',... 
               'TestBenchStimulus',  {'impulse', 'step', 'ramp', 'chirp', 'noise'},... 
               'InitializeTestBenchInputs', 'on',... 
               'GenerateCoSimBlock', 'on',... 
               'GenerateHDLTestbench', 'on');

% [EOF]
hehe 