function filter_generatehdl(filtobj)
%  FILTER_GENERATEHDL   Function to generate HDL for filter object.
%  Generated by MATLAB(R) 9.4 and Filter Design HDL Coder 3.1.3.
%  Generated on: 2022-03-03 12:56:37
%  -------------------------------------------------------------
%  HDL Code Generation Options:
%  FIRAdderStyle: tree
%  AddPipelineRegisters: on
%  TargetLanguage: Verilog
% 
%  Filter Settings:
%  Discrete-Time FIR Filter (real)
%  -------------------------------
%  Filter Structure  : Direct-Form FIR
%  Filter Length     : 11
%  Stable            : Yes
%  Linear Phase      : Yes (Type 1)

%  -------------------------------------------------------------

% Generating HDL code
generatehdl(filtobj, 'FIRAdderStyle', 'tree',... 
               'AddPipelineRegisters', 'on',... 
               'TargetLanguage', 'Verilog');

% [EOF]
