function Hd = Halfband_norm_15
%HALFBAND_NORM_15 Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 9.10 and DSP System Toolbox 9.12.
% Generated on: 05-Apr-2022 14:22:54

% Equiripple Halfband lowpass filter designed using the FIRHALFBAND
% function.

% All frequency values are in Hz.
Fs = 25;  % Sampling Frequency

N     = 14;      % Order
Fpass = 0.4375;  % Passband Frequency

% Calculate the coefficients using the FIRPM function.
b  = firhalfband(N, Fpass/(Fs/2));
Hd = dfilt.dffir(b);

% [EOF]
