function Hd = Halfband_Norm
%HALFBAND_NORM Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 9.10 and DSP System Toolbox 9.12.
% Generated on: 05-Apr-2022 16:47:27

% Equiripple Halfband lowpass filter designed using the FIRHALFBAND
% function.

% All frequency values are in MHz.
Fs = 12.5;  % Sampling Frequency

Fpass = 0.4375;          % Passband Frequency
Dpass = 0.057501127785;  % Passband Ripple

% Calculate the coefficients using the FIRPM function.
b  = firhalfband('minorder', Fpass/(Fs/2), Dpass);
Hd = dfilt.dffir(b);

% [EOF]
